# Generated by Django 3.2.9 on 2021-11-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=None, max_length=100, null=0),
        ),
        migrations.AddField(
            model_name='account',
            name='p_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Profile_Image', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(default=None, max_length=100, null=0),
        ),
    ]
