# Generated by Django 3.2.9 on 2021-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211115_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='p_image',
            field=models.ImageField(default='img/pic.jpg', upload_to='Profile_Image'),
        ),
    ]
