# Generated by Django 3.2.9 on 2021-11-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='p_image',
            field=models.ImageField(default='pic.jpg', upload_to='Profile_Image'),
        ),
    ]
