# Generated by Django 3.2.9 on 2021-11-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('heading1', models.CharField(max_length=255, null=True)),
                ('blog_desc1', models.TextField()),
                ('image1', models.ImageField(upload_to='blog_images')),
                ('heading2', models.CharField(max_length=255, null=True)),
                ('blog_desc2', models.TextField()),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('heading3', models.CharField(max_length=255, null=True)),
                ('blog_desc3', models.TextField()),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('heading4', models.CharField(max_length=255, null=True)),
                ('blog_desc4', models.TextField()),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('heading5', models.CharField(max_length=255, null=True)),
                ('blog_desc5', models.TextField()),
                ('image5', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
