# Generated by Django 3.2.9 on 2021-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
